In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn import metrics
from sklearn.model_selection import train_test_split

## Question 1

In [3]:
digit = load_digits()
x=digit.data
y=digit.target

In [4]:
x.shape , y.shape

((1797, 64), (1797,))

## Question 2

In [5]:
x = preprocessing.scale(x)
x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [6]:
df = pd.DataFrame(x)
df.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9     ...           54        55        56        57  \
0 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
1 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   
2 -0.059078 -0.624009    ...     0.259230 -0.209785 -0.023596 -0.299081   
3 -0.059078  1.879691    ...     1.072563 -0.209785 -0.023596 -0.299081   
4 -0.059078 -0.624009    ...    -0.757436 -0.209785 -0.023596 -0.299081   

         58        59        60        61        62        63  
0  0.086719  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -1.089383 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -1.089383 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.282736  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -1.089383 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

## Question 3

## Question 4

In [18]:
from sklearn.decomposition import PCA
pca = PCA(n_components=14)
principalComponents = pca.fit_transform(x)
principalComponents

array([[ 1.91420996, -0.95451722, -3.94604458, ..., -0.79337171,
         0.22604635, -0.19294553],
       [ 0.58900674,  0.92462587,  3.92481594, ...,  0.64611949,
        -0.03615694, -0.40473187],
       [ 1.30208617, -0.31720046,  3.0232844 , ..., -2.31239517,
        -0.56636107, -1.00903592],
       ...,
       [ 1.02259578, -0.14794525,  2.46996581, ...,  0.40058997,
        -0.41553033,  0.23660663],
       [ 1.07602891, -0.38088557, -2.45542206, ...,  0.60753782,
         0.18174112, -0.76787123],
       [-1.25758185, -2.22769787,  0.28380456, ...,  0.55805844,
         0.02327704,  0.67065907]])

In [8]:
#principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])

In [9]:
#principalDf

In [10]:
x = principalComponents
x.shape , y.shape

((1797, 16), (1797,))

In [19]:
from sklearn.linear_model import LogisticRegression
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2)

In [20]:
reg = LogisticRegression()
reg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [21]:
pred = reg.predict(X_test)

In [14]:
metrics.accuracy_score(Y_test,pred)*100

93.88888888888889

In [15]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        60
          1       0.94      0.86      0.90        59
          2       0.97      0.98      0.98        60
          3       0.90      0.96      0.93        55
          4       0.98      0.92      0.95        48
          5       0.95      0.96      0.95        55
          6       0.95      1.00      0.98        41
          7       0.95      1.00      0.97        58
          8       0.94      0.79      0.86        57
          9       0.81      0.94      0.87        47

avg / total       0.94      0.94      0.94       540



In [16]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test,pred))

[[59  0  0  0  1  0  0  0  0  0]
 [ 0 51  0  0  0  1  0  0  3  4]
 [ 0  0 59  0  0  0  0  1  0  0]
 [ 0  0  0 53  0  0  0  0  0  2]
 [ 0  0  0  0 44  1  0  1  0  2]
 [ 0  0  0  0  0 53  0  0  0  2]
 [ 0  0  0  0  0  0 41  0  0  0]
 [ 0  0  0  0  0  0  0 58  0  0]
 [ 0  2  2  6  0  0  2  0 45  0]
 [ 0  1  0  0  0  1  0  1  0 44]]
