In [29]:
from sklearn import datasets
import numpy as np
from sklearn import metrics
import pandas as pd
from sklearn.svm import SVC

## Question 1

In [56]:
digit = datasets.load_digits()
x = digit.data
y = digit.target

## Question 2

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)
x_train.shape, x_test.shape

((1347L, 64L), (450L, 64L))

## Question 3 

## (a)

In [32]:
model = SVC(kernel='linear')

In [33]:
model.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
pred = model.predict(x_test)

In [35]:
metrics.accuracy_score(y_test,pred)

0.9688888888888889

In [36]:
print(metrics.classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.98      1.00      0.99        47
          1       0.93      0.93      0.93        42
          2       0.98      1.00      0.99        45
          3       1.00      0.98      0.99        41
          4       1.00      1.00      1.00        44
          5       0.97      0.94      0.96        36
          6       1.00      0.98      0.99        50
          7       1.00      1.00      1.00        49
          8       0.88      0.93      0.91        46
          9       0.96      0.92      0.94        50

avg / total       0.97      0.97      0.97       450



In [37]:
print(metrics.confusion_matrix(y_test,pred))

[[47  0  0  0  0  0  0  0  0  0]
 [ 0 39  0  0  0  0  0  0  3  0]
 [ 0  0 45  0  0  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0  1  0]
 [ 0  0  0  0 44  0  0  0  0  0]
 [ 0  0  0  0  0 34  0  0  0  2]
 [ 1  0  0  0  0  0 49  0  0  0]
 [ 0  0  0  0  0  0  0 49  0  0]
 [ 0  2  1  0  0  0  0  0 43  0]
 [ 0  1  0  0  0  1  0  0  2 46]]


## (b)

In [38]:
model2 = SVC(kernel='poly')

In [39]:
model2.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [40]:
pred2 = model2.predict(x_test)

In [41]:
metrics.accuracy_score(y_test,pred2)

0.98

In [42]:
print(metrics.classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        47
          1       0.98      1.00      0.99        42
          2       1.00      1.00      1.00        45
          3       1.00      0.98      0.99        41
          4       1.00      1.00      1.00        44
          5       0.97      0.94      0.96        36
          6       1.00      0.98      0.99        50
          7       1.00      1.00      1.00        49
          8       0.92      0.96      0.94        46
          9       0.94      0.94      0.94        50

avg / total       0.98      0.98      0.98       450



In [43]:
print(metrics.confusion_matrix(y_test,pred2))

[[47  0  0  0  0  0  0  0  0  0]
 [ 0 42  0  0  0  0  0  0  0  0]
 [ 0  0 45  0  0  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0  1  0]
 [ 0  0  0  0 44  0  0  0  0  0]
 [ 0  0  0  0  0 34  0  0  0  2]
 [ 0  0  0  0  0  0 49  0  1  0]
 [ 0  0  0  0  0  0  0 49  0  0]
 [ 0  1  0  0  0  0  0  0 44  1]
 [ 0  0  0  0  0  1  0  0  2 47]]


## (c)

In [44]:
model3 = SVC(C=1.5)

In [45]:
model3.fit(x_train,y_train)

SVC(C=1.5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
pred3 = model3.predict(x_test)

In [47]:
metrics.accuracy_score(y_test,pred3)

0.4222222222222222

In [48]:
print(metrics.classification_report(y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.45      0.62        47
          1       1.00      0.55      0.71        42
          2       1.00      0.24      0.39        45
          3       1.00      0.59      0.74        41
          4       1.00      0.57      0.72        44
          5       0.12      1.00      0.22        36
          6       1.00      0.54      0.70        50
          7       1.00      0.20      0.34        49
          8       1.00      0.02      0.04        46
          9       1.00      0.24      0.39        50

avg / total       0.93      0.42      0.49       450



In [49]:
print(metrics.confusion_matrix(y_test,pred3))

[[21  0  0  0  0 26  0  0  0  0]
 [ 0 23  0  0  0 19  0  0  0  0]
 [ 0  0 11  0  0 34  0  0  0  0]
 [ 0  0  0 24  0 17  0  0  0  0]
 [ 0  0  0  0 25 19  0  0  0  0]
 [ 0  0  0  0  0 36  0  0  0  0]
 [ 0  0  0  0  0 23 27  0  0  0]
 [ 0  0  0  0  0 39  0 10  0  0]
 [ 0  0  0  0  0 45  0  0  1  0]
 [ 0  0  0  0  0 38  0  0  0 12]]


## (d)

In [50]:
model4 = SVC(kernel='sigmoid')

In [51]:
model4.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [52]:
pred4 = model4.predict(x_test)

In [53]:
metrics.accuracy_score(y_test,pred4)

0.08

In [54]:
print(metrics.classification_report(y_test,pred4))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        47
          1       0.00      0.00      0.00        42
          2       0.00      0.00      0.00        45
          3       0.00      0.00      0.00        41
          4       0.00      0.00      0.00        44
          5       0.08      1.00      0.15        36
          6       0.00      0.00      0.00        50
          7       0.00      0.00      0.00        49
          8       0.00      0.00      0.00        46
          9       0.00      0.00      0.00        50

avg / total       0.01      0.08      0.01       450



In [55]:
print(metrics.confusion_matrix(y_test,pred4))

[[ 0  0  0  0  0 47  0  0  0  0]
 [ 0  0  0  0  0 42  0  0  0  0]
 [ 0  0  0  0  0 45  0  0  0  0]
 [ 0  0  0  0  0 41  0  0  0  0]
 [ 0  0  0  0  0 44  0  0  0  0]
 [ 0  0  0  0  0 36  0  0  0  0]
 [ 0  0  0  0  0 50  0  0  0  0]
 [ 0  0  0  0  0 49  0  0  0  0]
 [ 0  0  0  0  0 46  0  0  0  0]
 [ 0  0  0  0  0 50  0  0  0  0]]
